### ISSUE TITLE
Support for python <3.11

### ISSUE THREAD

**Issue by ramilmsh** [bufbuild/protovalidate-python#110]
I would like to figure out why version 3.0.0 has dropped support for python <3.11 (https://github.com/bufbuild/protovalidate-python/issues/89) ?

1. PEP-604 seems to be supported starting with python 3.10, not 3.11. So why 3.11?
2. Why use a feature that has not yet necessarily reached wide-spread adoption in a library?

For us updating python version was not a huge pain, but it seems like this restriction might hurt adoption a lot. Python 3.11 is only one year old, i don't think it has reached the critical mass. Even 3.8 is not yet end-of-life

What am i missing?

**Comment by nicksnyder** [comment]
We didn't drop support for <3.11 in https://github.com/bufbuild/protovalidate-python/pull/90, versions earlier than 3.11 didn't ever work with to begin with because we were only ever testing against 3.11 in CI. The fact that the pyproject.toml advertised support for Python <3.11 was just wrong and an error we fixed in https://github.com/bufbuild/protovalidate-python/pull/90

Having said all that, we would love to support earlier versions of Python that are not yet EOL (3.8+ at the time of writing), but doing so hasn't reached the top of our priority list. We would definitely appreciate external contributions if you want to help!

Here are some notes we took when discussing https://github.com/bufbuild/protovalidate-python/pull/90:

> To effectively support older Python versions, we need to:
> * Develop locally on the oldest supported Python, so we're in the most restrictive environment by default.
> * Test in CI on all supported Python versions, so we know our package works with all the advertised Python versions.
> * Locally and in CI, deterministically install the correct version of each dependency…which varies by Python version.
> 
> Thoughts on how we should do this (this is just supposition):
> * pipenv seems like the wrong tool for this. It's (apparently) specifically designed to ship applications, so it doesn't support multiple Python versions at all. Migrate off pipenv to poetry + pyenv?
> * Use ruff check --fix to de-modernize our type annotations to work on Python 3.8. (Ruff is already part of the build.).
> * Poetry supports Python 3.8+. Ideally we'd do the same, changing `pyproject.toml` to match. If we can't go quite that far back, let's go as far as possible. We don't have any experience with Poetry, so if it is not the right tool for the job, let's do whatever Django, pytest, starlette, and other well-maintained projects do.

**Comment by nicksnyder** [comment]
Just merged a change to support 3.10 here: https://github.com/bufbuild/protovalidate-python/pull/111

**Comment by Alfus** [comment]
Released support for python >=3.8
